Require FP.Data.Ascii.
Require FP.Data.Function.
Require FP.Data.List.
Require FP.Data.N.
Require FP.Data.Nat.
Require FP.Data.Positive.
Require FP.Data.String.
Require FP.Data.Z.
Require FP.Data.Lens.

Export FP.Data.Ascii.CharNotation.
Export FP.Data.Function.FunctionNotation.
Export FP.Data.List.ListNotation.
Export FP.Data.N.NNotation.
Export FP.Data.Nat.NatNotation.
Export FP.Data.Positive.PositiveNotation.
Export FP.Data.String.StringNotation.
Export FP.Data.Z.ZNotation.
Export FP.Data.Lens.LensNotation.
